### ISSUE TITLE
Should we add merging/rebasing/squashing guidelines into CONTRIBUTING.md?

### ISSUE THREAD

**Issue by xylix** [apinf/openapi-designer#183]
We should maybe decide on the best workflow for our project and then follow it. All suggestions and arguments are welcome.

**Comment by tulir** [comment]
Normal merges or squash merges are the best in my opinion. Squash merges would provide a really clean master branch with one commit per feature. Normal merges create a more complex history, but no information is lost and since this is isn't a large-scale project, the history won't be too complex in any case.
