### ISSUE TITLE
Consider changing brand bar color

### ISSUE THREAD

**Issue by tulir** [apinf/openapi-designer#253]
We should consider changing the color of the brand bars. The current black branding is available in [master](https://dev.openapi.design/master/). A white example is available in [feature/white-branding](https://dev.openapi.design/feature/white-branding)

**Comment by tulir** [comment]
ping @Nazarah

**Comment by Nazarah** [comment]
Following are the comments to modify branding in Open API Designer.
1. Change the font awesome icon colors in #555555 instead #000000
2. Each icon should have 15 px top, bottom, left and right paddings
3. Make the footer color #555555 instead of #ffffff. Change the APInf logo accordingly.
4. Make the container background color #eaf0f3 or #f7f7f7 instead of #ffffff. This would bring contrast between all elements in the webpage (topbar, background, fields, etc.) Examples can be found in [HitchHQ](https://www.hitchhq.com/) and Market Mashapp (https://market.mashape.com/explore)

If you have confusions about colors and their compliments, please check the [Adobe CC color wheel](https://color.adobe.com/create/color-wheel/).

**Comment by tulir** [comment]
I've made the color changes, but I don't think we have space for that much padding. Should we make the icons smaller?
